name: Request a subscription key🔑
description: Request a subscription key for the Tzohar Digitali API Management
title: '[Request a subscription key]: '
labels:
- Subscription Key Request🔑
body:
- type: dropdown
  id: project-name
  attributes:
    label: Select project name📝
    options:
    - ffגג
  validations:
    required: true
- type: checkboxes
  id: api-environment
  attributes:
    label: Which api environments do you want to create a key for?🌐
    description: You may select more than one.
    options:
    - label: external
    - label: internal
  validations:
    required: true
