name: Request a subscription key
description: Request a subscription key for the Tzohar Digitali API Management
title: '[Request a subscription key]: '
labels:
- Subscription Key Request
body:
- type: dropdown
  id: project-name
  attributes:
    label: Select project name
    options:
    - dcvx
    - vladliel
    - tash
    - "注专转 拽专\t"
    - "转专 \t"
    - luzonb2r
    - d
    - dc
    - dc
    - dc
    - dc
    - dc
    - dc
    - dc
    - dc
    - 转
    - cpr-go
    - shuttle
    - 驻专拽
    - adi
    - 拽爪 拽
    - 驻专
    - 砖 拽专
    - 驻拽
    - secproj
    - ii
    - 专砖驻
    - dc
    - 专住 注
    - lielg
    - dc
    - 拽
    - sfdfsdfscvx
    - 专住 注
    -  1
    - hatch
    - 拽拽
  validations:
    required: true
- type: checkboxes
  id: api-environment
  attributes:
    label: Which api environments do you want to create a key for?
    description: You may select more than one.
    options:
    - label: external
    - label: internal
  validations:
    required: true
