name: Request a subscription key🔑
description: Request a subscription key for the Tzohar Digitali API Management
title: '[Request a subscription key]: '
labels:
- Subscription Key Request🔑
body:
- type: dropdown
  id: project-name
  attributes:
    label: Select project name📝
    options:
    - dcvxבלה
    - vladliel
    - tash
    - luzonb2r
    - dcבלה
    - לומדות
    - cpr-go
    - shuttle
    - פרויקט
    - adi
    - קבצי מוקדים
    - פטרול
    - שוב קורונה
    - מפקדים
    - secproj
    - מערכת הקריאה
    - ii
    - דרישופ
    - כרטיס עבודה
    - lielg
    - קיטבג
    - sfdfsdfscvxבלה
    - דוח 1
    - hatch
    - קודקוד
    - אתר המילואים
  validations:
    required: true
- type: input
  id: project-key-name
  attributes:
    label: Enter project key name🔑
    description: Must be written in english.
  validations:
    required: true
- type: checkboxes
  id: deployment-environment
  attributes:
    label: Which deployment environments do you want to create a key for?💻
    description: You may select more than one.
    options:
    - label: preprod
    - label: prod
  validations:
    required: true
- type: checkboxes
  id: api-environment
  attributes:
    label: Which api environments do you want to create a key for?🌐
    description: You may select more than one.
    options:
    - label: external
    - label: internal
  validations:
    required: true
- type: input
  id: project-officer-name
  attributes:
    label: Enter project officer name👨‍💻👩‍💻
  validations:
    required: true
- type: input
  id: project-officer-phone
  attributes:
    label: Enter project officer phone number📱
    description: Must be numbers.
  validations:
    required: true
