name: Create subscription key and add it to db after issue created

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create-subscription-key:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create subscription keys
        id: create-subscription-keys
        run: |
          PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 3')
          echo "preprod-external-key=$PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: Comment subscription keys
        run: |
          gh issue comment ${{ github.event.issue.html_url }} -b "${{ steps.create-subscription-keys.outputs.preprod-external-key }}"  

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.x

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # - name: Create subscription keys
      #   id: create-subscription-keys
      #   run: |
      #     PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 3')
      #     PROJECT_KEY_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 7')
      #     PREPROD_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 11 {print substr($0, 3, 3)}')
      #     PROD_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 12 {print substr($0, 3, 3)}')
      #     EXTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 16 {print substr($0, 3, 3)}')
      #     INTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 17 {print substr($0, 3, 3)}')
      #     if [[ "${PREPROD_CHECKBOX}" == "[X]" ]]; then
      #       if [[ "${EXTERNAL_CHECKBOX}" == "[X]" ]]; then
      #         preprod-external-key=$(python create-subscription-key.py --tenant-id "${{ vars.TENANT_ID }}" \
      #           --subscription-id "${{ vars.SUBSCRIPTION_ID }}" \
      #           --apim-rg-name "${{ vars.RESOURCE_GROUP }}" \
      #           --apim-name "${{ vars.APIM_NAME }}" \
      #           --client-id "${{ vars.CLIENT_ID }}" \
      #           --client-secret "${{ secrets.CLIENT_SECRET }}" \
      #           --subscription-key-name "${PROJECT_KEY_NAME}-preprod-external-hatch" \
      #           --product-name "${{ secrets.EXTERNAL_PRODUCT }}" \)
      #       fi
      #       if [[ "${INTERNAL_CHECKBOX}" == "[X]" ]]; then
      #         preprod-internal-key=$(python create-subscription-key.py --tenant-id "${{ vars.TENANT_ID }}" \
      #           --subscription-id "${{ vars.SUBSCRIPTION_ID }}" \
      #           --apim-rg-name "${{ vars.RESOURCE_GROUP }}" \
      #           --apim-name "${{ vars.APIM_NAME }}" \
      #           --client-id "${{ vars.CLIENT_ID }}" \
      #           --client-secret "${{ secrets.CLIENT_SECRET }}" \
      #           --subscription-key-name "${PROJECT_KEY_NAME}-preprod-internal-hatch" \
      #           --product-name "${{ secrets.INTERNAL_PRODUCT }}" \)
      #       fi
      #     fi
      #     if [[ "${PROD_CHECKBOX}" == "[X]" ]]; then
      #       if [[ "${EXTERNAL_CHECKBOX}" == "[X]" ]]; then
      #         prod-external-key=$(python create-subscription-key.py --tenant-id "${{ vars.TENANT_ID }}" \
      #           --subscription-id "${{ vars.SUBSCRIPTION_ID }}" \
      #           --apim-rg-name "${{ vars.RESOURCE_GROUP }}" \
      #           --apim-name "${{ vars.APIM_NAME }}" \
      #           --client-id "${{ vars.CLIENT_ID }}" \
      #           --client-secret "${{ secrets.CLIENT_SECRET }}" \
      #           --subscription-key-name "${PROJECT_KEY_NAME}-prod-external-hatch" \
      #           --product-name "${{ secrets.EXTERNAL_PRODUCT }}" \)
      #       fi
      #       if [[ "${INTERNAL_CHECKBOX}" == "[X]" ]]; then
      #         prod-internal-key=$(python create-subscription-key.py --tenant-id "${{ vars.TENANT_ID }}" \
      #           --subscription-id "${{ vars.SUBSCRIPTION_ID }}" \
      #           --apim-rg-name "${{ vars.RESOURCE_GROUP }}" \
      #           --apim-name "${{ vars.APIM_NAME }}" \
      #           --client-id "${{ vars.CLIENT_ID }}" \
      #           --client-secret "${{ secrets.CLIENT_SECRET }}" \
      #           --subscription-key-name "${PROJECT_KEY_NAME}-prod-internal-hatch" \
      #           --product-name "${{ secrets.INTERNAL_PRODUCT }}" \)
      #       fi
      #     fi

      # - name: Create subscription keys
      #   id: create-subscription-keys
      #   run: |
      #     PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 3')
      #     echo "::set-output name=preprod-external-key::$PROJECT_NAME"

      # - name: Comment subscription keys
      #   run: |
      #     gh issue comment ${{ github.event.issue.html_url }} -b "${{ steps.create-subscription-keys.outputs.preprod-external-key }}"  