name: Create subscription key and add it to db after issue created

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  create-subscription-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Get issue body data
        run: |
          PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 3')
          PROJECT_KEY_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 7')
          PREPROD_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 11 {print substr($0, 3, 3)}')
          PROD_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 12 {print substr($0, 3, 3)}')
          EXTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 16 {print substr($0, 3, 3)}')
          INTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 17 {print substr($0, 3, 3)}')
          PROJECT_OFFICER_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 21')
          PROJECT_OFFICER_PHONE=$(echo "${{ github.event.issue.body }}" | awk 'NR == 25')
        
      - name: Print data
        run: |
          echo "${PROJECT_NAME}"
          echo "${PROJECT_KEY_NAME}"


      # - name: Create subscription keys
      #   run: |
      #     PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 3')
      #     PROJECT_KEY_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 7')
      #     PREPROD_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 11 {print substr($0, 3, 3)}')
      #     PROD_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 12 {print substr($0, 3, 3)}')
      #     EXTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 16 {print substr($0, 3, 3)}')
      #     INTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 17 {print substr($0, 3, 3)}')
      #     PROJECT_OFFICER_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 21')
      #     PROJECT_OFFICER_PHONE=$(echo "${{ github.event.issue.body }}" | awk 'NR == 25')
      #     if [[ "${PREPROD_CHECKBOX}" == "[X]" ]]; then
      #       if [[ "${EXTERNAL_CHECKBOX}" == "[X]" ]]; then
      #         python create-subscription-key.py --tenant-id "${{ vars.TENANT_ID }}" \
      #           --subscription-id "${{ vars.SUBSCRIPTION_ID }}" \
      #           --apim-rg-name "${{ vars.RESOURCE_GROUP }}" \
      #           --apim-name "${{ vars.APIM_NAME }}" \
      #           --client-id "${{ vars.CLIENT_ID }}" \
      #           --client-secret "${{ secrets.CLIENT_SECRET }}" \
      #           --subscription-key-name "${PROJECT_KEY_NAME}-preprod-external-hatch" \
      #           --product-name "${{ env.EXTERNAL_PRODUCT }}" \
      #       fi
      #       if [[ "${INTERNAL_CHECKBOX}" == "[X]" ]]; then
      #         python create-subscription-key.py --tenant-id "${{ vars.TENANT_ID }}" \
      #           --subscription-id "${{ vars.SUBSCRIPTION_ID }}" \
      #           --apim-rg-name "${{ vars.RESOURCE_GROUP }}" \
      #           --apim-name "${{ vars.APIM_NAME }}" \
      #           --client-id "${{ vars.CLIENT_ID }}" \
      #           --client-secret "${{ secrets.CLIENT_SECRET }}" \
      #           --subscription-key-name "${PROJECT_KEY_NAME}-preprod-internal-hatch" \
      #           --product-name "${{ env.INTERNAL_PRODUCT }}" \
      #       fi
      #     fi
      #     if [[ "${PROD_CHECKBOX}" == "[X]" ]]; then
      #       if [[ "${EXTERNAL_CHECKBOX}" == "[X]" ]]; then
      #         python create-subscription-key.py --tenant-id "${{ vars.TENANT_ID }}" \
      #           --subscription-id "${{ vars.SUBSCRIPTION_ID }}" \
      #           --apim-rg-name "${{ vars.RESOURCE_GROUP }}" \
      #           --apim-name "${{ vars.APIM_NAME }}" \
      #           --client-id "${{ vars.CLIENT_ID }}" \
      #           --client-secret "${{ secrets.CLIENT_SECRET }}" \
      #           --subscription-key-name "${PROJECT_KEY_NAME}-prod-external-hatch" \
      #           --product-name "${{ env.EXTERNAL_PRODUCT }}" \
      #       fi
      #       if [[ "${INTERNAL_CHECKBOX}" == "[X]" ]]; then
      #         python create-subscription-key.py --tenant-id "${{ vars.TENANT_ID }}" \
      #           --subscription-id "${{ vars.SUBSCRIPTION_ID }}" \
      #           --apim-rg-name "${{ vars.RESOURCE_GROUP }}" \
      #           --apim-name "${{ vars.APIM_NAME }}" \
      #           --client-id "${{ vars.CLIENT_ID }}" \
      #           --client-secret "${{ secrets.CLIENT_SECRET }}" \
      #           --subscription-key-name "${PROJECT_KEY_NAME}-prod-internal-hatch" \
      #           --product-name "${{ env.INTERNAL_PRODUCT }}" \
      #       fi
      #     fi



      #     if [[ "${EXTERNAL_CHECKBOX}" == "[X]" ]]; then
            
      #       echo "EXTERNAL_KEY_NAME=${PROJECT_NAME}-external-hatch" >> ${GITHUB_ENV}
      #     fi
      #     if [[ "${INTERNAL_CHECKBOX}" == "[X]" ]]; then
      #       echo "INTERNAL_KEY_NAME=${PROJECT_NAME}-internal-hatch" >> ${GITHUB_ENV}
      #     fi

      # - name: Print keys
      #   run: |
      #     echo "${{ env.EXTERNAL_KEY_NAME }}"
      #     echo "${{ env.INTERNAL_KEY_NAME }}"
