name: Issue created

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:
          # EXTERNAL_KEY="external-hatch-${PROJECT_NAME}"
          # INTERNAL_KEY="internal-hatch-${PROJECT_NAME}"
          # if [ $INTERNAL_CHECKBOX == "[X]"]; then
          #   echo "internal"
jobs:
  create-subscription-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create subscription names
        run: |
          PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 3')
          EXTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 7 {print substr($0, 3, 3)}')
          INTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 8 {print substr($0, 3, 3)}')
          if [[ "${EXTERNAL_CHECKBOX}" == "[X]" ]]; then
            echo "EXTERNAL_KEY='external-hatch-${PROJECT_NAME}'" >> ${GITHUB_ENV}
            EXTERNAL_KE="external-hatch-${PROJECT_NAME}"
          else
            EXTERNAL_KE="None"
          fi
          if [[ "${INTERNAL_CHECKBOX}" == "[X]" ]]; then
            echo "INTERNAL_KEY='internal-hatch-${PROJECT_NAME}'" >> ${GITHUB_ENV}
            INTERNAL_KE="internal-hatch-${PROJECT_NAME}"
          else
            INTERNAL_KE="None"
          fi

      - name: Print keys
        run: |
          echo "${{ env.EXTERNAL_KEY }}"
          echo "${{ env.INTERNAL_KEY }}"
