name: Label issues

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  get-and-save-issue-body:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: echo "KEY=or-${{ github.event.issue.body }}-external" >> ${GITHUB_ENV}

      - name: Validate issue body
        run: PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 2')
      
      - name: Print project
        run: echo "$PROJECT_NAME"
      
      - name: Print project
        run: echo "or-fsfs"
