name: Label issues

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  get-and-save-issue-body:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate issue body
        run: |
          PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 2')
          EXTERNAL=$(echo "${{ github.event.issue.body }}" | awk 'NR == 4')
          INTERNAL=$(echo "${{ github.event.issue.body }}" | awk 'NR == 5')
      
      -name: Print project
       run: |
          echo "$PROJECT_NAME"
      
      -name: Print external
       run: |
          echo "$EXTERNAL"
      
      -name: Print internal
       run: |
          echo "$INTERNAL"
