name: Label issues

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  get-and-save-issue-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create key name env variable
        run: echo "KEY=or-${{ github.event.issue.body }}-external" >> ${GITHUB_ENV}

      - name: G
        run: echo "${{ env.ISSUE_BODY }}"
