name: Issue created

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  create-subscription-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get subscription info
        run: |
          PROJECT_NAME=$(echo "${{ github.event.issue.body }}" | awk 'NR == 3')
          EXTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 7 {print substr($0, 3, 3)}')
          EXTERNAL=$(echo "${{ github.event.issue.body }}" | awk 'NR == 7 {if (substr($0, 3, 3) == "[X]") print substr($0, 7)}')
          INTERNAL=$(echo "${{ github.event.issue.body }}" | awk 'NR == 8 {if (substr($0, 3, 3) == "[X]") print substr($0, 7)}')
          INTERNAL_CHECKBOX=$(echo "${{ github.event.issue.body }}" | awk 'NR == 8 {print substr($0, 3, 3)}')
          echo "$PROJECT_NAME"
          echo "$EXTERNAL"
          echo "$INTERNAL"
          echo "$EXTERNAL_CHECKBOX"
          echo "$INTERNAL_CHECKBOX"
